// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxLhzYriVT5bmQulhJBVbTMrBQttSgKTw',
    appId: '1:679771843332:web:03d237439e472beabc7e51',
    messagingSenderId: '679771843332',
    projectId: 'biswasshoppingbd-5c83b',
    authDomain: 'biswasshoppingbd-5c83b.firebaseapp.com',
    storageBucket: 'biswasshoppingbd-5c83b.firebasestorage.app',
    measurementId: 'G-XGD1XMH5FG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiWpYU2qvdxf1JQ8ZSjXs8n3PSTlilOH8',
    appId: '1:679771843332:android:d45e8b5eb9670006bc7e51',
    messagingSenderId: '679771843332',
    projectId: 'biswasshoppingbd-5c83b',
    storageBucket: 'biswasshoppingbd-5c83b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqwbG2ibnkqC5mBU2yQS6T4wiN9wGE7cg',
    appId: '1:679771843332:ios:f04a629887d3924dbc7e51',
    messagingSenderId: '679771843332',
    projectId: 'biswasshoppingbd-5c83b',
    storageBucket: 'biswasshoppingbd-5c83b.firebasestorage.app',
    androidClientId: '679771843332-sgbk3lv4lqdkhnsaqqfpj4td43ssm8s2.apps.googleusercontent.com',
    iosClientId: '679771843332-rd7r5ksjfck7td2qluq67equa7l652hs.apps.googleusercontent.com',
    iosBundleId: 'com.example.biswasShopAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqwbG2ibnkqC5mBU2yQS6T4wiN9wGE7cg',
    appId: '1:679771843332:ios:f04a629887d3924dbc7e51',
    messagingSenderId: '679771843332',
    projectId: 'biswasshoppingbd-5c83b',
    storageBucket: 'biswasshoppingbd-5c83b.firebasestorage.app',
    androidClientId: '679771843332-sgbk3lv4lqdkhnsaqqfpj4td43ssm8s2.apps.googleusercontent.com',
    iosClientId: '679771843332-rd7r5ksjfck7td2qluq67equa7l652hs.apps.googleusercontent.com',
    iosBundleId: 'com.example.biswasShopAdminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxLhzYriVT5bmQulhJBVbTMrBQttSgKTw',
    appId: '1:679771843332:web:03d237439e472beabc7e51',
    messagingSenderId: '679771843332',
    projectId: 'biswasshoppingbd-5c83b',
    authDomain: 'biswasshoppingbd-5c83b.firebaseapp.com',
    storageBucket: 'biswasshoppingbd-5c83b.firebasestorage.app',
    measurementId: 'G-XGD1XMH5FG',
  );

}